### ISSUE TITLE
Build is failing due to myocamlbuild.ml

### ISSUE THREAD

**Issue by seliopou** [mmottl/sqlite3-ocaml#2]
While trying to install this package via OPAM, I got the following error:

```
#=== ERROR while installing sqlite3.2.0.7 =====================================#
# opam-version 1.2.0
# os           linux
# command      ocaml setup.ml -build
# path         /home/frenetic/.opam/4.01.0/build/sqlite3.2.0.7
# compiler     4.01.0
# exit-code    1
# env-file     /home/frenetic/.opam/4.01.0/build/sqlite3.2.0.7/sqlite3-2135-5f1023.env
# stdout-file  /home/frenetic/.opam/4.01.0/build/sqlite3.2.0.7/sqlite3-2135-5f1023.out
# stderr-file  /home/frenetic/.opam/4.01.0/build/sqlite3.2.0.7/sqlite3-2135-5f1023.err
### stdout ###
# ...[truncated]
# Turn ocaml profile flag on: .......................... false
# Compiler support generation of .cmxs.: ............... true
# OCamlbuild additional flags: ......................... 
# Strict compile-time checks: .......................... true
# Create documentations: ............................... true
# Compile tests executable and library and run them: ... false
# ocamldoc: ............................................ /home/frenetic/.opam/4.01.0/bin/ocamldoc
# 
# /home/frenetic/.opam/4.01.0/bin/ocamlopt.opt unix.cmxa -I /home/frenetic/.opam/4.01.0/lib/ocaml/ocamlbuild /home/frenetic/.opam/4.01.0/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/frenetic/.opam/4.01.0/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# Failure: pkg-config failed for cflags.
### stderr ###
# Package sqlite3 was not found in the pkg-config search path.
# Perhaps you should add the directory containing `sqlite3.pc'
# to the PKG_CONFIG_PATH environment variable
# No package 'sqlite3' found
# E: Failure("Command ''/home/frenetic/.opam/4.01.0/bin/ocamlbuild' lib/libsqlite3_stubs.a lib/dllsqlite3_stubs.so lib/sqlite3.cma lib/sqlite3.cmxa lib/sqlite3.a lib/sqlite3.cmxs -tag debug' terminated with error code 2")
```

I tried building from source, and then got the following type error in `myocamlbuild.ml`:

```
$ make
ocaml setup.ml -build 
+ /usr/local/bin/ocamlopt.opt unix.cmxa -I /usr/local/lib/ocaml/ocamlbuild /usr/local/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/local/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "myocamlbuild.ml", line 753, characters 41-56:
Error: This expression has type MyOCamlbuildBase.t
       but an expression was expected of type MyOCamlbuildFindlib.conf
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
E: Failure("Command ''/usr/local/bin/ocamlbuild' lib/libsqlite3_stubs.a lib/dllsqlite3_stubs.so lib/sqlite3.cma lib/sqlite3.cmxa lib/sqlite3.a lib/sqlite3.cmxs -tag debug' terminated with error code 10")
*** Error code 1

Stop.
make: stopped in /tmp/sqlite3-ocaml
```

**Comment by mmottl** [comment]
You may want to verify that sqlite3 is properly installed on your system.  Try the following command:
```sh
pkg-config sqlite3 --print-errors
```

It should return with exit code 0 and no other output if that's the case, or print an error message otherwise.

Building from source probably failed, because your (old) system compiler was used instead of the newer one in OPAM.

I'm pretty sure that you will succeed once `pkg-config` lists sqlite3 as installed.

**Comment by rleonid** [comment]
I'm experiencing this problem as well on the latest branch. And I also can't build sqlite3 from scratch. Something funky in your latest commit modified `myocamlbuild.ml` to introduce that type error (we checked with the previous version and things compiled).

**Comment by seliopou** [comment]
To follow-up, the version of the compiler I was using is 4.01.0 (which is also included in the output provided). The `_oasis` file in the repo says indicates a supported OCaml version of 3.12 and above.

I've tried compiling&mdash;with sqlite3 installed&mdash; on Ubuntu 13.10 as well as FreeBSD 10.0. On cc215db, it builds fine.

**Comment by rleonid** [comment]
Same, I'm also compiling with 4.01.0.

I fixed the typo to allow it to compile in my fork, waiting on PR. I also added an extra guard because `pkg-config

**Comment by mmottl** [comment]
Strange, I had tested this issue before and couldn't reproduce it on my machine, but now I also got this failure.  Something must have been different about my configuration.  Anyway, I have applied Leo's patch, which should fix the problem.  Thanks!

**Comment by rleonid** [comment]
Thanks Markus!
