### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by wwood** [mmottl/sqlite3-ocaml#20]
Hi,

I'm wondering which license sqlite3-ocaml is under, since in the COPYING file it gives an expat-style license, while the `opam` file says "LGPL-2.1+ with OCaml linking exception".

Thanks, ben.

**Comment by mmottl** [comment]
Thanks for noticing, the original license is indeed an Expat-style license.  The Oasis file incorrectly referred to the LGPL which then showed up in OPAM as such.  The fixed package should be in OPAM soon.
