### ISSUE TITLE
documentation: looking for  type mapping  SQLite <-> ocaml-sqlite

### ISSUE THREAD

**Issue by klartext** [mmottl/sqlite3-ocaml#21]
SQLite-documentation says, there are the following functions, accessing values of certain types of columns:

    sqlite3_column_blob()
    sqlite3_column_bytes()
    sqlite3_column_bytes16()
    sqlite3_column_count()
    sqlite3_column_double()
    sqlite3_column_int()
    sqlite3_column_int64()
    sqlite3_column_text()
    sqlite3_column_text16()
    sqlite3_column_type()
    sqlite3_column_value()

ocaml-sqlite has:

type t = 
| 	NONE
| 	NULL
| 	INT of int64
| 	FLOAT of float
| 	TEXT of string
| 	BLOB of string

What is the used mapping?

And how is the mapping from SQL-statements mapped to Data-type?
For example if there is VARCHAR(<n>), or any other SQL-type,
how to access it with ocaml-sqlite?

And: if reading a database is working by automatic coercion of the SQLite-types to ocaml-sqlite Data-type; what is done in case of the other direction? Mapping from a lower number of types to a higher number of types results in what?
Is that a safe operation?
Does it influence performance, if SQLIte adapts the types automatically?

**Comment by mmottl** [comment]
The function `sqlite3_column_type` is used in the C-bindings to determine the type of a column.  The type can only take one of five values as described here: https://www.sqlite.org/c3ref/c_blob.html

The OCaml variant names make the mapping obvious.  Should SQLite3 introduce new types that the OCaml bindings don't support, then `NONE` would be returned.
