### ISSUE TITLE
Notice about thread-safety

### ISSUE THREAD

**Issue by paurkedal** [mmottl/sqlite3-ocaml#25]
For the `db` and `stmt` types there is a notice not to use them "WITHIN THREADS OTHER THAN THE ONE THAT CREATED IT".  Comparing with [the Sqlite3 documentation on thread safety](https://sqlite.org/threadsafe.html):

> SQLite supports three different threading modes:
>
> 1. Single-thread. In this mode, all mutexes are disabled and SQLite is unsafe to use in more than a single thread at once.
>
> 2. Multi-thread. In this mode, SQLite can be safely used by multiple threads provided that no single database connection is used simultaneously in two or more threads.
>
> 3. Serialized. In serialized mode, SQLite can be safely used by multiple threads with no restriction.

In the worst case scenario, sqlite3 is compiled for single-thread mode, in which case it would not be safe to use the library simultaneously from different threads even using different handles.  This is probaby not very common, though.  The default mode is serialized, and I would guess most distribution at least enables multi-thread.

If we assume at least multi-thread mode, then the requirement seems too strong.  In particular, it should be safe to use a `db` or `stmt` from different threads, as long as access is locked by a per-`db` and per-`stmt` mutex.  This is relevant to applications using `Lwt_preemptiev` and `Async.In_thread`.  In `Async.In_thread` there is a `thread` argument which may help, but `Lwt_preemptive` does not give control over which thread to use.

Can we assume the OCaml bindings does not bring in any additional threading issues?  If so, maybe it would be better to refer to or relay the Sqlite3 documentation on the point?

**Comment by mmottl** [comment]
Thanks for the hint!  This documentation appears rather outdated.  I have updated it to refer users to the SQLite3 online manual wrt. thread safety.

According to the manual, it should typically be safe to access SQLite3 from different threads with barely any restrictions though users are well-advised to determine whether their installation is configured according to needs.  I think it would be good practice for developers to generally assume the "Multi-thread" configuration.  It's easy enough to develop your applications with the associated restrictions in mind and shouldn't cause any performance issues.  "Single-thread" is almost surely only used in scenarios where the developer expects it (e.g. embedded systems).
