### ISSUE TITLE
link flags

### ISSUE THREAD

**Issue by kkirstein** [mmottl/sqlite3-ocaml#26]
Hi,

after updating from `sqlite3 4.1.3` I get a linking error when building a project, which uses sqlite3 (same error for `4.2.0` & `4.3.0)`:

    ** Cannot resolve symbols for C:/Opt/OCaml64/home/kayuwekirstein/.opam/4.04.2+mingw64/lib\sqlite3\libsqlite3_stubs.a(sqlite3_stubs.o):
     pthread_getspecific
     pthread_key_create
     pthread_setspecific
    File "caml_startup", line 1:
    Error: Error during linking

I can fix the linking by providing an additional `-lpthread` switch to the jbuild config of my library, which seems to work on Windows (cygwin with MinGW toolchain), but still fails on WSL/BashForWindows (which is basically an Ubuntu 16.04).
After googling, I found out that this might be an issue with the order of the link flags on the command line, but I have no clue, on how to control that with jbuilder.
Anyway, does anybody have an idea, why it worked fine with 4.1.3 and is different with later versions (I wouldn't call it broken)? Maybe one can give an advice, on how to setup a project depending on sqlite3 (ideally with using jbuilder). I couldn't find a suitable one by reverse search of opam deps.

**Comment by mmottl** [comment]
Thanks for the report.  It seems that most people directly or indirectly link with the OCaml threads library, which is why they typically never see this issue.  Not sure why this popped up just know for you.  I have added an explicit linker flag and made a new release.  Concerning WSL/BashForWindows, I have no idea what to do about this, especially since I can't test potential fixes.  If you find a solution, please submit a pull request.

**Comment by kkirstein** [comment]
Thanks for the fast answer. With the additional -lpthread flag (in sqlite3), my project now compiles (and links) on WSL/BashForWindows, which is (for me) the expected behaviour. On Cygwin/MinGW it still needs the -pthread flag in my library build setup. Looks like `ld` is behaving differently on these architectures..
I will do some more analysis and keep you updated...

**Comment by kkirstein** [comment]
OK, it also works for Cygwin/MinGW now. I don't know what went wrong yesterday, maybe I messed up with `opam source/pin`...

Thanks for your help.
