### ISSUE TITLE
Building: Jbuilder has been renamed to Dune

### ISSUE THREAD

**Issue by klartext** [mmottl/sqlite3-ocaml#27]
Jbuilder has been renamed to Dune
  https://github.com/ocaml/dune

**Comment by mmottl** [comment]
I don't think it is available as such in the current OPAM repository.  I'll switch my packages once Dune has been rolled out.

**Comment by vog** [comment]
Meanwhile, Dune has been rolled out, so it seems safe to switch.

**Comment by mmottl** [comment]
A new distribution switching to Dune has already been released last October.  This issue is fixed.
