### ISSUE TITLE
opam install failing

### ISSUE THREAD

**Issue by andiejs** [mmottl/sqlite3-ocaml#28]
Seems to be an EOF error... 
Any help would be much appreciated!

> opam ins sqlite3
The following actions will be performed:
  ∗  install sqlite3 4.3.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[sqlite3] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of sqlite3 failed at "jbuilder build -p sqlite3 -j 4".

=== ERROR while installing sqlite3.4.3.2 =====================================#
 opam-version 1.2.2
 os           linux
 command      jbuilder build -p sqlite3 -j 4
 path         /home/eliot/.opam/4.06.1/build/sqlite3.4.3.2
 compiler     4.06.1
 exit-code    1
 env-file     /home/eliot/.opam/4.06.1/build/sqlite3.4.3.2/sqlite3-20071-58c514.env
 stdout-file  /home/eliot/.opam/4.06.1/build/sqlite3.4.3.2/sqlite3-20071-58c514.out
 stderr-file  /home/eliot/.opam/4.06.1/build/sqlite3.4.3.2/sqlite3-20071-58c514.err
 stderr ###
 -> stdout:
 [...]
  | ast_impl_magic_number: Caml1999M022
  | ast_intf_magic_number: Caml1999N022
  | cmxs_magic_number: Caml1999D022
  | cmt_magic_number: Caml1999T022
 -> stderr:
 Fatal error: exception End_of_file
 Raised at file "src/import0.ml" (inlined), line 351, characters 22-32
 Called from file "src/configurator.ml", line 511, characters 13-22
 Called from file "src/config/discover.ml", line 42, characters 2-1023

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install sqlite3 4.3.2
No changes have been performed

=-=- sqlite3.4.3.2 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing. `opam depext sqlite3.4.3.2' may help you find the
   correct installation for your system.

...
> opam depext sqlite3.4.3.2
 Detecting depexts using flags: x86_64 linux linuxmint
 No extra OS packages requirements found.

**Comment by mmottl** [comment]
It's possible that there is a problem with `pkg-config` on your system.  Can you verify that

```sh
pkg-config --cflags sqlite3
pkg-config --libs sqlite3
```

return something meaningful?  You can also modify file `src/config/discover.ml` in the `sqlite3-ocaml` distribution to see what lines are being read from `pkg-config`.

**Comment by mmottl** [comment]
Probably not an issue anymore.  Closing...
