### ISSUE TITLE
README links 404

### ISSUE THREAD

**Issue by juszczakn** [mmottl/sqlite3-ocaml#30]
Documentation link leads to https://mmottl.github.io/sqlite3-ocaml/api/sqlite3 which 404s

**Comment by mmottl** [comment]
Thanks, this is fixed.  There seems to be a problem right now with the way `topkg` generates documentation (see https://github.com/dbuenzli/topkg/issues/129).  Once this is fixed, it should be easier to automatically generate correct API documentation.
