### ISSUE TITLE
Static linking against libsqlite3?

### ISSUE THREAD

**Issue by vog** [mmottl/sqlite3-ocaml#31]
Is it possible to link an OCaml program statically to libsqlite3, i.e. that it links against `libsqlite3.a` instead of `libsqlite3.so.0`?

If so, is it also possible to do that with an OPAM-based installation of sqlite3-ocaml?

**Comment by mmottl** [comment]
I'm not sure, but one could conceivably suppress these linker warnings by passing suitable flags.  `musl` may be a suitable alternative to `glibc` that might allow you to work around this problem.

**Comment by vog** [comment]
Unfortunately, compiling for `musl` on a `glibc`-based host system is not that straight forward. I hope I'll find a solution that does not involve Docker build containers - or chroot/containers/VM at all, for that matter.

Related: https://github.com/ocaml/dune/issues/1249
