### ISSUE TITLE
Cannot compile on windows

### ISSUE THREAD

**Issue by Chimrod** [mmottl/sqlite3-ocaml#45]
I'm using the [OCaml for windows](https://fdopen.github.io/opam-repository-mingw/) repository, and the installation fails as `pkg-config` is not recognized as a command.

Replacing all references from `pkg-config` to `pkgconf` in `discover.ml` solve the problem, but I am not able to propose a clean PR for this.

**Comment by mmottl** [comment]
It seems that this is a deeper issue: https://access.redhat.com/discussions/4734691

I'm not sure about the impact of potential incompatibilities.  In any case, it seems that at least RHEL 8 uses a symlink from `pkg-config` to `pkgconf`.  Maybe this is just missing on your platform?  Such a widespread utility as `pkg-config` should probably not just disappear.

**Comment by mmottl** [comment]
More Windows compatibility improvements will be released soon.
