### ISSUE TITLE
Warning when compiling C stubs under 4.14

### ISSUE THREAD

**Issue by nojb** [mmottl/sqlite3-ocaml#54]
![image](https://user-images.githubusercontent.com/113560/174776454-b9b51b4d-5781-47e0-a46b-7a8a3bd84400.png)

Can probably be fixed by moving the `sqlite3.h` include *before* the Caml headers.

**Comment by mmottl** [comment]
I can't replicate this with the latest OCaml version (5.2.0). Please reopen in case the problem persists.

**Comment by nojb** [comment]
> I can't replicate this with the latest OCaml version (5.2.0). Please reopen in case the problem persists.

OCaml 5.2.0 doesn't include the legacy symbols (`callback` vs `caml_callback`, etc) so indeed no warning is emitted. The warning is still emitted for 4.14, though. But OK, let's not worry too much about this. Thanks!
