### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by ygrek** [mmottl/sqlite3-ocaml#9]
```
Fatal error: exception Failure("This function always errors")
W: Test 'test_error' fails: Command '/home/ygrek/work/contrib/sqlite3-ocaml/_build/test/test_error.native' terminated with error code 2
E: Failure("Tests had a 16.67% failure rate")
Makefile:13: recipe for target 'test' failed
make: *** [test] Error 1
```

This started to happen with v4.0.0.

Here is the output from v3.0.0 which works ok : 
```
This function always errors
Bind threw an error
```

**Comment by mmottl** [comment]
Thanks, I've improved the testing application.  The library actually behaved as it should, but the testing application didn't.  I guess you don't need an immediate release.  Installation should still be possible.
